
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESleftCONCATCHARS CONCAT IMPRIMIRRESULTADO LPAREN MINUS NUMBER PLUS QUOTE RPAREN TIMESinicio : expresionexpresion : expresion PLUS expresion\n| expresion MINUS expresion\n| expresion TIMES expresionexpresion : expresion CONCAT expresionexpresion : IMPRIMIRRESULTADO LPAREN expresion RPARENexpresion : NUMBERexpresion : LPAREN expresion RPARENexpresion : QUOTE expresion QUOTEexpresion : CHARS'
    
_lr_action_items = {'IMPRIMIRRESULTADO':([0,4,6,8,9,10,11,12,],[3,3,3,3,3,3,3,3,]),'NUMBER':([0,4,6,8,9,10,11,12,],[5,5,5,5,5,5,5,5,]),'LPAREN':([0,3,4,6,8,9,10,11,12,],[4,12,4,4,4,4,4,4,4,]),'QUOTE':([0,4,5,6,7,8,9,10,11,12,14,15,16,17,18,20,21,22,],[6,6,-7,6,-10,6,6,6,6,6,21,-2,-3,-4,-5,-8,-9,-6,]),'CHARS':([0,4,6,8,9,10,11,12,],[7,7,7,7,7,7,7,7,]),'$end':([1,2,5,7,15,16,17,18,20,21,22,],[0,-1,-7,-10,-2,-3,-4,-5,-8,-9,-6,]),'PLUS':([2,5,7,13,14,15,16,17,18,19,20,21,22,],[8,-7,-10,8,8,-2,-3,-4,-5,8,-8,-9,-6,]),'MINUS':([2,5,7,13,14,15,16,17,18,19,20,21,22,],[9,-7,-10,9,9,-2,-3,-4,-5,9,-8,-9,-6,]),'TIMES':([2,5,7,13,14,15,16,17,18,19,20,21,22,],[10,-7,-10,10,10,10,10,-4,-5,10,-8,-9,-6,]),'CONCAT':([2,5,7,13,14,15,16,17,18,19,20,21,22,],[11,-7,-10,11,11,11,11,11,-5,11,-8,-9,-6,]),'RPAREN':([5,7,13,15,16,17,18,19,20,21,22,],[-7,-10,20,-2,-3,-4,-5,22,-8,-9,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'expresion':([0,4,6,8,9,10,11,12,],[2,13,14,15,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> expresion','inicio',1,'p_inicio','parser.py',12),
  ('expresion -> expresion PLUS expresion','expresion',3,'p_expresion_binaria','parser.py',16),
  ('expresion -> expresion MINUS expresion','expresion',3,'p_expresion_binaria','parser.py',17),
  ('expresion -> expresion TIMES expresion','expresion',3,'p_expresion_binaria','parser.py',18),
  ('expresion -> expresion CONCAT expresion','expresion',3,'p_expresion_concatenacion','parser.py',28),
  ('expresion -> IMPRIMIRRESULTADO LPAREN expresion RPAREN','expresion',4,'p_expresion_imprimir','parser.py',32),
  ('expresion -> NUMBER','expresion',1,'p_expresion_numero','parser.py',37),
  ('expresion -> LPAREN expresion RPAREN','expresion',3,'p_expresion_parentesis','parser.py',41),
  ('expresion -> QUOTE expresion QUOTE','expresion',3,'p_expresion_repeat','parser.py',45),
  ('expresion -> CHARS','expresion',1,'p_repeat','parser.py',49),
]
